### ISSUE TITLE
Help needed with CPS twinning 

### ISSUE THREAD

**Issue by sebavarghese** [sbaresearch/cps-twinning#4]
Hi,

I am trying to use the cps twinning framework, with the example specification file (CandyFactory.aml). I am facing some issues with the instantiation of PLC node (as I am getting socket errors). I would like to get clarifications on a few questions as put below:
1. Is it possible to run this framework without a physical twin running along? As of now, I am not using the state replication module. I have installed mininet-wifi and matiec and cloned to the cps twinning repository. When I run ‘make twinning’ and ‘twinning misc/specification/CandyFactory.aml’, the topology is built correctly. But when I try to run ‘show_tags PLC1’ or get/set tags, it throws a socket error as seen in the attached file.
![twinning](https://user-images.githubusercontent.com/62105008/110601144-ebffad00-8184-11eb-8e93-026894b3be20.PNG)

Note: I even tried using the code available as tag v0.0.2 (without state replication), still I face the same issues as mentioned above.
2. Also, I believe a physical twin must be run parallel with the framework. Is this correct?

I would like to know whether I miss configuring anything else. Your help is much appreciated.

**Comment by sebavarghese** [comment]
![twinning3](https://user-images.githubusercontent.com/62105008/110635443-62170a80-81ab-11eb-896c-a818c27e81a4.PNG)

**Comment by sebavarghese** [comment]
Before hitting this issue, there was an error which read: 
  __File "/home/seba/cps-twinning/env/lib/python2.7/site-packages/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/seba/cps-twinning/env/lib/python2.7/site-packages/kafka/client_async.py", line 830, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable__

For this, I have commented out the Kafka lines in twins.py code. However, on uncommenting them, I see some logs in cps-twinning.log. 

![image](https://user-images.githubusercontent.com/62105008/110636910-23824f80-81ad-11eb-8ba0-956db779389f.png)

**Comment by MatthiasEckhart** [comment]
Sorry, yes, you are correct after running `twinning *.aml`, some files in the `/tmp/cps-twinning` folder should have been created.

Probably, the easiest option would be to run [Apache Kafka](https://kafka.apache.org/) and adapt the IP address in the [constants.py](https://github.com/sbaresearch/cps-twinning/blob/master/cpstwinning/constants.py#L12) accordingly. The Kafka errors should then be gone, provided that your machine that runs CPS Twinning is able to reach your Kafka broker.

**Comment by sebavarghese** [comment]
After running Apache Kafka and changing IP address, kafka errors are resolved.
![image](https://user-images.githubusercontent.com/62105008/110648608-2420e300-81b9-11eb-96d7-a0e6b273f03e.png)


But still, the main error exists.
cpstwinning> show_tags PLC1
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    net=net)
  File "run.py", line 17, in __init__
    CLI(self.net)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/wifi/cli.py", line 10, in __init__
    CLI.__init__(self, mininet, stdin=sys.stdin, script=None)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/cli.py", line 68, in __init__
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/cli.py", line 103, in run
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/seba/cps-twinning/cpstwinning/cli.py", line 64, in do_show_tags
    output(node.show_tags())
  File "/home/seba/cps-twinning/cpstwinning/twins.py", line 121, in show_tags
    result = self.__send_message(ShowTagsMessage())
  File "/home/seba/cps-twinning/cpstwinning/twins.py", line 65, in __send_message
    self.__send(msg)
  File "/home/seba/cps-twinning/cpstwinning/twins.py", line 61, in __send
    self.__create_connection()
  File "/home/seba/cps-twinning/cpstwinning/twins.py", line 58, in __create_connection
    self.conn = Client(address)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 308, in SocketClient
    s.connect(address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

**Comment by MatthiasEckhart** [comment]
Okay, thanks for the update. Are you using the forked version of [Mininet-WiFi](https://github.com/MatthiasEckhart/mininet-wifi)?

**Comment by sebavarghese** [comment]
Yes, I am using the forked version.

**Comment by MatthiasEckhart** [comment]
Okay, good. This version of CPS Twinning is not being actively developed any longer, and I currently don't have a running setup on my machine. Probably, the fastest way to resolve this issue is to send me your VM. Would this be an option for you?

**Comment by 1939552724** [comment]
Hello,when I run the command "show_tags PLC1", the program raises a error. On line 127 of  the function “show_tags(self)” in "twins.py", the program raises a error like "KeyError: name". Could you help me solve this problem? Thank you!
![show_tags-Keyerror](https://user-images.githubusercontent.com/53972901/170903364-d7907aa9-1161-4d81-bfe5-d2224c0fe495.png)
